# Generated by Django 5.2.7 on 2025-10-30 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TICKET', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_name', models.CharField(max_length=200)),
                ('from_address', models.TextField()),
                ('from_city', models.CharField(max_length=100)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('siret', models.CharField(blank=True, max_length=14)),
                ('rcs', models.CharField(blank=True, max_length=100)),
                ('is_ei', models.BooleanField(default=False)),
                ('to_name', models.CharField(max_length=200)),
                ('to_address', models.TextField()),
                ('to_city', models.CharField(max_length=100)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('service_date_start', models.DateField(blank=True, null=True)),
                ('service_date_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vat_exempt', models.BooleanField(default=False)),
                ('payment_terms', models.TextField(blank=True)),
                ('late_fee_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('recovery_fee', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
                ('autoliquidation', models.BooleanField(default=False)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('ticket', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='TICKET.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CORE.invoice')),
            ],
        ),
    ]
