# Generated by Django 5.2.7 on 2025-11-09 11:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom/Entreprise')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(max_length=200, verbose_name='Nom/Entreprise émetteur')),
                ('from_address', models.TextField(verbose_name='Adresse émetteur')),
                ('from_city', models.CharField(blank=True, max_length=100, verbose_name='Ville émetteur')),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='Email émetteur')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('rcs', models.CharField(blank=True, max_length=100, verbose_name='RCS')),
                ('is_ei', models.BooleanField(default=False, verbose_name='Entrepreneur Individuel')),
                ('to_name', models.CharField(max_length=200, verbose_name='Nom/Entreprise client')),
                ('to_address', models.TextField(verbose_name='Adresse client')),
                ('to_city', models.CharField(blank=True, max_length=100, verbose_name='Ville client')),
                ('to_email', models.EmailField(blank=True, max_length=254, verbose_name='Email client')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Numéro de facture')),
                ('invoice_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('service_date_start', models.DateField(blank=True, null=True, verbose_name='Début de prestation')),
                ('service_date_end', models.DateField(blank=True, null=True, verbose_name='Fin de prestation')),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total HT')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Taux TVA (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant TVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total TTC')),
                ('is_vat_exempt', models.BooleanField(default=False, verbose_name='Franchise de TVA')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Modalités de paiement')),
                ('late_fee_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Pénalités de retard (%)')),
                ('recovery_fee', models.BooleanField(default=True, verbose_name='Indemnité de recouvrement (40€)')),
                ('autoliquidation', models.BooleanField(default=False, verbose_name='Autoliquidation')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='État')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='CORE.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-created_at'],
                'unique_together': {('user', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire HT')),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total ligne')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='CORE.invoice')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name="Nom de l'entreprise")),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('siret', models.CharField(blank=True, max_length=20, verbose_name='SIRET')),
                ('rcs', models.CharField(blank=True, max_length=100, verbose_name='RCS')),
                ('is_ei', models.BooleanField(default=False, verbose_name='Entrepreneur Individuel')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
