# Generated by Django 5.2.7 on 2025-10-30 01:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de commande')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender_name', models.CharField(max_length=200, verbose_name='Nom/Entreprise expéditeur')),
                ('sender_address', models.TextField(verbose_name='Adresse expéditeur')),
                ('sender_city', models.CharField(max_length=100, verbose_name='Ville expéditeur')),
                ('sender_email', models.EmailField(blank=True, max_length=254, verbose_name='Email expéditeur')),
                ('sender_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone expéditeur')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Nom destinataire')),
                ('recipient_address', models.TextField(verbose_name='Adresse destinataire')),
                ('recipient_city', models.CharField(max_length=100, verbose_name='Ville destinataire')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Email destinataire')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone destinataire')),
                ('recipient_instructions', models.CharField(blank=True, max_length=200, verbose_name='Instructions de livraison')),
                ('shipping_date', models.DateField(verbose_name="Date d'expédition")),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Poids (kg)')),
                ('length', models.IntegerField(verbose_name='Longueur (cm)')),
                ('width', models.IntegerField(verbose_name='Largeur (cm)')),
                ('height', models.IntegerField(verbose_name='Hauteur (cm)')),
                ('carrier', models.CharField(choices=[('colissimo', 'Colissimo'), ('chronopost', 'Chronopost'), ('mondial_relay', 'Mondial Relay'), ('ups', 'UPS'), ('dpd', 'DPD'), ('other', 'Autre')], max_length=50, verbose_name='Transporteur')),
                ('carrier_other', models.CharField(blank=True, max_length=100, verbose_name='Autre transporteur')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de suivi')),
                ('is_fragile', models.BooleanField(default=False, verbose_name='Fragile')),
                ('is_insured', models.BooleanField(default=False, verbose_name='Assuré')),
                ('insurance_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant assuré')),
                ('cash_on_delivery', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Contre-remboursement')),
                ('signature_required', models.BooleanField(default=False, verbose_name='Signature obligatoire')),
                ('recipient_message', models.CharField(blank=True, max_length=100, verbose_name='Message au destinataire')),
                ('pdf_generated', models.BooleanField(default=False)),
                ('invoice_generated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Étiquette',
                'verbose_name_plural': 'Étiquettes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valeur unitaire')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='TICKET.ticket')),
            ],
            options={
                'verbose_name': 'Article du colis',
                'verbose_name_plural': 'Articles du colis',
            },
        ),
    ]
